### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by dewebdes** [marioperezhurtado/Boble#1]
**no such file or directory, open '/root/Boble/node_modules/tailwindcss/oxide-node-api-shim/package.json'**

### What is this ERROR?

**Comment by marioperezhurtado** [comment]
I installed it again using npm and it didn't give me any error, maybe try reinstalling? If you still have problems, send me a screenshot of the error. Thx :D

**Comment by marioperezhurtado** [comment]
Similar problem: https://stackoverflow.com/questions/38143558/npm-install-resulting-in-enoent-no-such-file-or-directory
